config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :matches do
    member do
      post 'set_stone'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do 
    controller :gameplay do 
      get 'get_state'
      post 'set_stone'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :match_players
  before_save :store_board
  before_update do
    if @_board.won? 
      self.ended = true
    end   
  end
  after_find do
    @_board = Marshal::load(self.board) if self.board
  end
  before_create :prepare_board
  def prepare_board 
    @_board = TickTackToe3d.new unless @_board 
    store_board
  end
  def get_state 
    @_board.get_board.to_s
  end
  def get_board
    @_board
  end
  def store_board
    self.board = Marshal::dump(@_board)
  end
  def player_x
    self.match_players.where(side: 1).first
  end
  def player_o
    self.match_players.where(side: 0).first
  end

  def player_x=(player_id)
    self.match_players.where(side: 1).destroy_all
    self.match_players.new(:player_id => player_id, :side => 1)
  end
  def player_o=(player_id)
    self.match_players.where(side: 0).destroy_all
    self.match_players.new(:player_id => player_id, :side => 0)
  end
  def get_last_position
    return nil unless self.last_position
    pos = self.last_position.split ':'
    return {
      x: pos[0], 
      y: pos[1], 
      z: pos[2]
    }
  end
  def randomize
    side = self.get_board.turn
    position = Position.from_params({:x => rand(0..3), :y => rand(0..3), :z => rand(0..3)})
    self.last_position = position.to_s
    if side == "o"
      self.get_board.player2_move(position)
    else
      self.get_board.player1_move(position)
    end
    self.save!
  end
end

app/models/match_player.rb
class MatchPlayer < ApplicationRecord
  belongs_to :match
  belongs_to :player
  
  before_create :set_hash
  def set_hash
    begin 
      self.key = IdGenerator.generate 
    end until MatchPlayer.where(:key => self.key).empty?
  end
  def set_stone(position)
    begin
      raise GameplayException.new("Can't play this match") if  self.match.ended
      if self.side == 1
        method = "player1_move"
      else
        method = "player2_move"
      end
      position = Position.from_params(position)
      self.match.get_board.send(method, position)
      self.match.last_position = position.to_s
      self.match.save
    rescue GameplayException => ex
      render json: {:error => ex.message} 
    end
  end
  def get_state
    board = self.match.get_board
    {
      turn: board.turn,
      board: board,
      ended: self.match.ended ? 1 : 0,
      player: self.side == 1 ? "x" : "o" 
    }
  end
end

app/models/player.rb
class Player < ApplicationRecord
  validates :uniq_hash, uniqueness: true
  before_create :set_hash
  def set_hash
    begin 
      self.uniq_hash = IdGenerator.generate 
    end until Player.where(:uniq_hash => self.uniq_hash).empty?
  end
end

app/controllers/api/gameplay_controller.rb
class Api::GameplayController < ApplicationController
  skip_before_action :verify_authenticity_token
  rescue_from GameplayException, with: :gameplay_exception
  before_action do
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
  def set_stone
    sleep(2)
    set_game
    @game.set_stone params[:position]
    render :json =>{:ok => true}
  end
  def get_state
    set_game
    render json: @game.get_state
  end
  private 
  def set_game
    @game = MatchPlayer.where(:key => params[:key]).first
  end

  def stone_parameters
    params.require(:position).permit(:x, :y, :z)
  end
  def gameplay_exception(exception)
    render :json => {:error => exception.message }, :status => 400
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :set_stone
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
    raise
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
#  def update
#    respond_to do |format|
#      if @match.update(match_params)
#        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
#      else
#        format.html { render :edit }
#      end
#    end
#  end

  # DELETE /matches/1
  # DELETE /matches/1.json
#  def destroy
#    @match.destroy
#    respond_to do |format|
#      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
#    end
#  end
  def set_stone
    set_match 
    raise GameplayException.new("Can't play this match") if  @match.ended
    side = @match.get_board.turn
    puts side
    position = Position.from_params(params.fetch(:position).permit(:x, :y, :z))
    @match.last_position = position.to_s
    if side == "o"
      @match.get_board.player2_move(position)
    else
      @match.get_board.player1_move(position)
    end
    @match.save!
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.fetch(:match).permit(:player_o, :player_x)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :uniq_hash)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Programment
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg
  .inputs
    %label Player X
    = select("match", "player_x", Player.all.collect {|p| [p.name, p.id]})
    %label Player O
    = select("match", "player_o", Player.all.collect {|p| [p.name, p.id]})
  .actions
    = f.submit 'Save'

app/views/matches/_visualization.html.haml
-board = @match.get_board.get_board.get_fields
-last_position = @match.get_last_position
-winning_line = @match.get_board.winning_line if @match.ended
-if winning_line
  -wl = []
  -winning_line.each do |point|
    -wl.push({x: point.x, y: point.y, z:point.z})
-board.each_with_index do |row, x|
  .ttt-row>
    -row.each_with_index do |slice, y|
      .ttt-slice>
        -slice.each_with_index do |field, z|
          .ttt-field{x: x, y:y, z:z, class: ((last_position and last_position[:x].to_i == x and last_position[:y].to_i == y and last_position[:z].to_i == z) ? "highlight" : "")+" "+((wl and wl.include?({x:x, y:y, z:z})) ? "winner" : " ")  }>
            -if board[x][y][z] 
              = board[x][y][z] 
            -else 
              &nbsp;
    %br/

app/views/matches/edit.html.haml
%h1 Editing match

= render 'form'

= link_to 'Show', @match
\|
= link_to 'Back', matches_path

app/views/matches/index.html.haml
%h1 Listing matches

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @matches.each do |match|
      %tr
        %td= link_to 'Show', match

%br

= link_to 'New Match', new_match_path

app/views/matches/new.html.haml
%h1 New match

= render 'form'

= link_to 'Back', matches_path

app/views/matches/show.html.haml
%p#notice= notice
:javascript 
  setTimeout(function() {
    document.location.reload();
  }, 1000);
.col-xs-1
  X
  = @match.player_x.key
.col-xs-6
  %div#visualization
    = render partial: 'visualization'
.col-xs-1
  O
  = @match.player_o.key
= link_to 'Edit', edit_match_path(@match)
\|
= link_to 'Back', matches_path

app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1 Listing players

%table
  %thead
    %tr
      %th Name
      %th Uniq hash
      %th
      %th
      %th

  %tbody
    - @players.each do |player|
      %tr
        %td= player.name
        %td= player.uniq_hash
        %td= link_to 'Show', player
        %td= link_to 'Edit', edit_player_path(player)
        %td= link_to 'Destroy', player, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Player', new_player_path

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @player.name
%p
  %b Uniq hash:
  = @player.uniq_hash

= link_to 'Edit', edit_player_path(@player)
\|
= link_to 'Back', players_path